server:
  port: 8888

spring:
  datasource:
    name: source
    url: jdbc:mysql://localhost:3306/source
    username: root
    password: xxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      root: info
      com.lrm: debug
    file: log/blog.log


      # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20